trigger:
 none

pool: Fortify-test

steps:

- task: FortifySCA@7
  inputs:
    applicationType: 'dotnet'
    fortifyProjects: '**\*.sln'
    fortifyBuildId: 'azure-dotnet'
    runFortifyRulepackUpdate: true
    fortifyScanType: 'LocalScan'
    runFortifyUpload: true
    fortifyApplicationName: 'Azure-dotnet'
    fortifyApplicationVersion: '2.0'

- task: MSBuild@1
  inputs:
    solution: '**/*.sln'
    clean: true